made RawData class and applied to each notebooks from other repositories.
taro-kuroda-5228/auto_trading pull request #11
Opened 2021-11-04 12:27 UTC by taro-kuroda-5228

2021-11-05 00:16 UTC, atsushimemet requested changes
@taro-kuroda-5228 
gitを扱えるようになって、初めての本格的なコード作成ですね!
勉強されたことがわかるコーディングで大変嬉しいです😊

いくつかレビューさせて頂きました。
ご自身で修正可能な点は修正し、不明点等はqaチャンネルを活用して質問してください!

それでは修正のほど、よろしくお願いいたします。

2021-11-05 00:16 UTC, atsushimemet commented on auto_trading/raw_data_100.py
> +        df = df.iloc[::-1,1:][0:100]
@taro-kuroda-5228 
日次降順にする処理として、[::-1]は一つの選択肢です。記述も短く済みますし良いと思います!
ただ、一見してわかりにくいという問題があります。前述のdatetime列をindex化が終了していれば、sort_valuesを使って並び替え処理を行なっておくと、この部分のコードの見通しが良くなります。

そして、[0:100]で取得する日数を指定する処理ですが、とても良いです。
次はこの処理に汎用性を持たせるために、外部から取得したい日数を指定できるようにしましょう。
(合わせて、ファイル名をraw_data_100.pyからraw_data.pyに変更しましょう。)
(HINT: __init__内に取得したい日数を。。。)

2021-11-05 00:16 UTC, atsushimemet commented on auto_trading/raw_data_100.py
> +        time_series_data()
@taro-kuroda-5228 
if __name__の記載があり、自主的に勉強してくださったのだなと感じ、大変嬉しいです!
一方で、今回この記述は不要なのです。理由は、対話的に理解していきましょう。

質問ですが、
(1) ここにif __name__ == "__main__"の記述を行ったのはなぜでしょうか?
(2) クラス内の__init__関数の役割を3行程度で教えてください。
(3) if __name__以下の記述をインデントを一つ上げ(左側に動かし)、auto_traiding/auto_traidingに移動し、`python raw_data.py`を実行してみてください。(前述したファイル名をraw_data_100.pyからraw_data.pyに変更、を終えた後に実行してみてください。)

2021-11-05 00:16 UTC, atsushimemet commented on auto_trading/raw_data_100.py
> +        time_series_data()
@taro-kuroda-5228 
また、ファイルの最終行には空行を入れましょう。
(慣習的なものですが、詳細は[こちら](https://msfukui.hatenablog.com/entry/2018/12/18/071145)に記述されています。)

2021-11-05 00:16 UTC, atsushimemet commented on auto_trading/raw_data_100.py
> +        time_series_data()
@taro-kuroda-5228 
raw_data_30.pyは削除しましょう。
そして、raw_data_30.pyで実現したことをraw_data.pyで実現できるようにしてください。

2021-11-05 09:05 UTC, taro-kuroda-5228 commented on auto_trading/raw_data_100.py
> +            pass
了解致しました！

2021-11-05 09:21 UTC, taro-kuroda-5228 commented on auto_trading/raw_data_100.py
> +        symbol_data = None
これはyahoo finance api2の公式サイトに載っていたデータを取得するためのコードをそのままコピペした形になります！

2021-11-05 09:22 UTC, taro-kuroda-5228 commented on auto_trading/raw_data_100.py
> +        df["datetime"] = pd.to_datetime(df.timestamp, unit="ms")
すいません、この処理はすでにDataMart classに組み込んでしまったのですが、RawData classに移した方が良いですか？？

2021-11-05 11:17 UTC, taro-kuroda-5228 commented on auto_trading/raw_data_100.py
> +                self.name += '.T'
すいません、調べてみたのですがヘルパー関数の書き方がよく分かりませんでした、、、

2021-11-05 12:04 UTC, taro-kuroda-5228 commented on auto_trading/raw_data_100.py
> +        time_series_data()
⑴外からモジュールをimportした時のみ、その関数を使えるようにするのがif name == "main"の働きという認識です。今回まさしくその動作を行っているのであった方が良いかなと思いつけました。
⑵繰り返しモジュールを使う場合、引数をそのたびに初期化するという認識でした。
⑶エラーが出ました。%run raw_data.pyではモジュールをインポートしたわけではないので、⑴の通りなのかなと思いましたが、、、

2021-11-05 12:14 UTC, taro-kuroda-5228 commented
deleted raw_data_30.py and raw_data_100.py. 
created raw_data.py

2021-11-05 14:07 UTC, atsushimemet requested changes
@taro-kuroda-5228 
後少しです!docstringの参考サイトは[こちら](https://google.github.io/styleguide/pyguide.html#s3.8.3-functions-and-methods)です。

2021-11-06 03:05 UTC, taro-kuroda-5228 commented
修正しました！ご確認よろしくお願いします！

2021-11-06 03:16 UTC, atsushimemet commented on auto_trading/raw_data.py
> +"""
@taro-kuroda-5228 
言葉汚いですが、めちゃくちゃ素晴らしいdoc stringです。感動しました。

- 1行目より前にモジュール自体のdocstringも書いておいてください。
  - RawData class is includedなど、簡単な記載で構いません。
- 場所を以下に移動しておいてください!
```
class RawData
    <ここに移動してください。>
    def __init__(...)
```

2021-11-06 03:42 UTC, atsushimemet requested changes
@taro-kuroda-5228 
後少しです!

2021-11-06 03:42 UTC, atsushimemet commented on auto_trading/raw_data.py
> +"""
@taro-kuroda-5228 
言葉汚いですが、めちゃくちゃ素晴らしいdoc stringです。感動しました。

- 1行目より前にモジュール自体のdocstringも書いておいてください。
  - RawData class is includedなど、簡単な記載で構いません。
- 場所を以下に移動しておいてください!
```
class RawData
    <ここに移動してください。>
    def __init__(...)
```

2021-11-06 03:42 UTC, atsushimemet commented on auto_trading/raw_data.py
> +        If nationality is Japan, add '.T' at the end of name
@taro-kuroda-5228 
本当に素敵です。docstring書くの上手な方は、そもそもプログラム書くのが上手い傾向にあります。

2021-11-06 03:42 UTC, atsushimemet commented on auto_trading/raw_data.py
> +
@taro-kuroda-5228 
小さなことですが、ファイルの最終行に空行を入れておいてください。

2021-11-06 03:42 UTC, atsushimemet commented on auto_trading/raw_data.py
> +        symbol_data = None
@taro-kuroda-5228 
Nameというクラスを持つ、name.pyを生成しても良いかもしれません。

このPR内では行うべきではないので、本PRをマージした後、[イシューの書き方を学ぶタスク](https://www.wrike.com/open.htm?id=786882845)に取り組み、name.pyに関するイシューを起票してください。

2021-11-06 03:42 UTC, atsushimemet commented on auto_trading/raw_data.py
> +            sys.exit(1)
@taro-kuroda-5228
SymbolDataというクラスを持つ、symbol_data.pyを生成しても良いかもしれません。

このPR内では行うべきではないので、本PRをマージした後、[イシューの書き方を学ぶタスク](https://www.wrike.com/open.htm?id=786882845)に取り組み、symbol_data.pyに関するイシューを起票してください。

2021-11-06 03:42 UTC, atsushimemet commented on auto_trading/raw_data.py
> +        df = df.loc[self.start_date:end_date,:]
@taro-kuroda-5228
preprocess_symbol_dataという関数をRawDataクラス内に生成しても良いかもしれません。

このPR内では行うべきではないので、本PRをマージした後、[イシューの書き方を学ぶタスク](https://www.wrike.com/open.htm?id=786882845)に取り組み、preprocess_symbol_dataという関数のイシューを起票してください。

2021-11-06 04:40 UTC, taro-kuroda-5228 commented on auto_trading/raw_data.py
> +
すいません、少し勘違いしていたのですがこの場合のファイルの最終行というのはreturn dfの下ではなく上という認識で正しいでしょうか？

2021-11-06 04:47 UTC, taro-kuroda-5228 commented
可能な範囲で修正しています！

2021-11-07 11:48 UTC, atsushimemet approved these changes
@taro-kuroda-5228 
遅くなりました。
よくかけています。squash & mergeをしましょう。

2021-11-07 11:48 UTC, atsushimemet commented on auto_trading/raw_data.py
> +
いえ、下で構いません。
今確認すると、下に入っていますが、下に入っていないという警告記号が出るので、バグかもしれません。
一旦、本件は無視で構いません。

2021-11-07 12:33 UTC, merged