made name.py
taro-kuroda-5228/auto_trading pull request #15
Opened 2021-11-07 13:31 UTC by taro-kuroda-5228

2021-11-08 01:26 UTC, atsushimemet requested changes
@taro-kuroda-5228 
お疲れ様です。まず、docstringがとても読みやすいです。日本人の方とは思えません。素晴らしいです。

いくつか修正点、コメントを記載してありますので、ご対応・ご確認のほどよろしくお願い致します。

2021-11-08 01:26 UTC, atsushimemet commented on auto_trading/name.py
> +    my_share = Name(name, nationality).get_my_share
@taro-kuroda-5228 
細かいところですが、Argsの下のnameの記述前にあるような4つスペースの後ろからmy_share = ...と、記載されているといいと思います。

2021-11-08 01:26 UTC, atsushimemet commented on auto_trading/name.py
> +
@taro-kuroda-5228 
空行を削除しましょう。

2021-11-08 01:26 UTC, atsushimemet commented on auto_trading/name.py
> +
@taro-kuroda-5228 
このように本質的でないミスなどは、コード自動整形ツールに任せてしまいましょう。
例えばBlackというものがあります。詳細は[こちら](https://qiita.com/tsu_0514/items/2d52c7bf79cd62d4af4a)をご覧ください。

この場で、簡単に説明すると、例えば上記で指摘させて頂いた空行は、Blackを使用すれば、ファイルの保存時に消えてくれます。なのでBlackをインストールするタスクを[こちら](https://www.wrike.com/open.htm?id=788411772)に起票致しました。優先順位は低いのでご自身のタイミングで実施してください。

また、これまでは~~.pyを作成する際は、ブラウザから起動したjupyter lab上で行っていたかと思いますが、jupyter labはnotebookの作成を行う際の利用にとどめ、~~.pyを作成する際はVSCodeで行うと良いと思います。

2021-11-08 01:26 UTC, atsushimemet commented on auto_trading/name.py
> +        return self.name
@taro-kuroda-5228 
add_suffix_tseの返り値を使用している箇所がないので、こちらの`return self.name`は記述しなくて良いと思います。
別の用途があって、`return self.name`を記述されている場合は、お知らせください。

2021-11-08 01:26 UTC, atsushimemet commented on auto_trading/name.py
> +    def get_my_share(self):
@taro-kuroda-5228 
返り値のtype hintを書きましょう。

2021-11-08 11:31 UTC, taro-kuroda-5228 commented
changed bugs mentioned above.

2021-11-08 12:10 UTC, atsushimemet requested changes
@taro-kuroda-5228 
あと少しです。修正頑張りましょう。

2021-11-08 12:10 UTC, atsushimemet commented on auto_trading/name.py
> +
@taro-kuroda-5228 
言葉足らずでした。空行は関数の下です。
今は消さなくていいです。あとでBlackで一括して消しましょう。

2021-11-08 12:10 UTC, atsushimemet commented on auto_trading/name.py
> +
@taro-kuroda-5228
ここの空行も同様です。
今は消さなくていいです。あとでBlackで一括して消しましょう。

2021-11-08 12:10 UTC, atsushimemet commented on auto_trading/name.py
> +    def get_my_share(self)-> method:
@taro-kuroda-5228 
methodというtypeはありません。
組み込みのtype関数で表示されるものがtypeです。
これを踏まえてtype hintを記載してください。

2021-11-09 12:22 UTC, atsushimemet approved these changes
@taro-kuroda-5228 
大変お疲れ様でした。squash & mergeお願いします!

2021-11-10 10:16 UTC, merged